version: '3.9'

services:

  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    container_name: server
    ports:
      - 5000:5000

    
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    links:
      - server