version: '3.9'

services:

  server:
    build:
      dockerfile: Dockerfile
      context: "./server"
    ports:
      - 5000:5000
    links:
      - client
    
  client:
    build:
      dockerfile: Dockerfile
      context: ./client

    ports:
      - 3000:3000